// Generated by `yarn story-ids` — do not edit. 5 harnesses in the playground.
//
// Fills Playwright's `Stories` interface so `mount('…')` offers the list and checks the props.
// See scripts/generate-story-ids.mjs for why this is generated and why it is one file per scope.

declare module '@playwright/test' {
  interface Stories {
    StoreContextHarness: (typeof import('../shared/lib/__tests__/create-store-context.story'))['StoreContextHarness'];
    UseAnnouncerHarness: (typeof import('../shared/lib/__tests__/use-announcer.story'))['UseAnnouncerHarness'];
    UseFormHarness: (typeof import('../shared/lib/__tests__/use-form.story'))['UseFormHarness'];
    UseStoreHarness: (typeof import('../shared/lib/__tests__/use-store.story'))['UseStoreHarness'];
    SelectionDropdownHarness: (typeof import('../shared/ui/__tests__/selection-dropdown.story'))['SelectionDropdownHarness'];
  }
}

export {};
