export { AlertContent as Alert } from '@/entities/modal-template/ui/vanilla/shared/content/AlertContent';
export { ContentTransition } from '@/entities/modal-template/ui/vanilla/shared/content/ContentTransition';
export { Detail } from '@/entities/modal-template/ui/vanilla/shared/content/Detail';
export { DetailList } from '@/entities/modal-template/ui/vanilla/shared/content/DetailList';
export { Heading } from '@/entities/modal-template/ui/vanilla/shared/content/Heading';
export { Hint } from '@/entities/modal-template/ui/vanilla/shared/content/Hint';
export { Message } from '@/entities/modal-template/ui/vanilla/shared/content/Message';
export { OverflowContainer } from '@/entities/modal-template/ui/vanilla/shared/content/OverflowContainer';
export { OverflownTypography } from '@/entities/modal-template/ui/vanilla/shared/content/OverflownTypography';
export { Section } from '@/entities/modal-template/ui/vanilla/shared/content/Section';
